profile:
  default: website

bibliography: references.bib

editor_options:
  chunk_output_type: console

editor:
  markdown:
    wrap: 72

execute:
  warning: false
  message: false
  cache: false
  freeze: auto

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
